---
sudo: required

language: c

env:
  global:
    - ANDROID_HOME=${HOME}/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

matrix:
  include:
    - os: linux
      env: HOST=arm-eabi RUNTESTFLAGS="--target_board android DEJAGNU="/opt/.travis/site.exp"

before_install:
  - wget -q https://dl.google.com/android/repository/android-ndk-r20b-linux-x86_64.zip -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - mkdir ~/.android
  - echo 'count=0' > ~/.android/repositories.cfg
  - yes | sdkmanager --licenses >/dev/null
  - echo y | sdkmanager --no_https "platform-tools" >/dev/null
  - echo y | sdkmanager --no_https "tools" >/dev/null
  - echo y | sdkmanager --no_https "build-tools;28.0.3" >/dev/null
  - echo y | sdkmanager --no_https "platforms;android-28" >/dev/null
  - find ${ANDROID_HOME} -type f

install:
  - travis_wait 30 ./.travis/install.sh

script:
  - if ! test x"$MEVAL" = x; then eval ${MEVAL}; fi
  - travis_wait 115 sleep infinity &
  - ./.travis/build.sh
