---
sudo: required

language: cpp

matrix:
  include:
    - os: windowns
      env: HOST=i686-w64-mingw32

before_install:
  - if test x"$MEVAL" != x; then eval ${MEVAL}; fi

install:
  - travis_wait 30 ./.travis/install.sh

script:
  - if ! test x"$MEVAL" = x; then eval ${MEVAL}; fi
  - ./.travis/build.sh
