---
sudo: required

language: cpp

matrix:
  include:
    - os: linux
      env: HOST=i686-w64-mingw32 MEVAL='export CC="i686-w64-mingw32-gcc-win32" && CXX="i686-w64-mingw32-g++-win32"' LIBFFI_TEST_OPTIMIZATION=-O2 RUNTESTFLAGS="--target_board wine-sim" DEJAGNU="$TRAVIS_BUILD_DIR/.travis/site.exp" CONFIGURE_OPTIONS="--disable-shared"

before_install:
  - if test x"$MEVAL" != x; then eval ${MEVAL}; fi

install:
  - travis_wait 30 ./.travis/install.sh

script:
  - if ! test x"$MEVAL" = x; then eval ${MEVAL}; fi
  - travis_wait 45 sleep infinity &
  - ./.travis/build.sh
