---
sudo: required

language: android

matrix:
  include:
    - os: linux
      env: HOST=arm8-android RUNTESTFLAGS="--target_board android DEJAGNU="/opt/.travis/site.exp"

before_install:
  - android list sdk --no-ui --all --extended
  - if test x"$MEVAL" != x; then eval ${MEVAL}; fi

install:
  - travis_wait 30 ./.travis/install.sh

script:
  - if ! test x"$MEVAL" = x; then eval ${MEVAL}; fi
  - travis_wait 115 sleep infinity &
  - ./.travis/build.sh
